##preload = /home/javier/.config/hypr/fondo-javier.png
#wallpaper = , /home/javier/.config/hypr/fondo-javier.png
#splash = true

######################################################################
#                                                                    #
##IMPORTANTE: Colocar slackware-backgrounds-blue.png en ~/Imágenes/  #
#                                                                    #
######################################################################

wallpaper {
    monitor = eDP-1
    path = ~/Imágenes/slackware-background-blue.png
    fit_mode = fill
##    splash = false
}

