##preload = /home/javier/.config/hypr/fondo-javier.png
#wallpaper = , /home/javier/.config/hypr/fondo-javier.png
#splash = true

wallpaper {
    monitor = eDP-1
    path = /usr/share/backgrounds/mate/desktop/slackware-background-blue.png
    fit_mode = fill
##    splash = false
}

