##preload = /home/javier/.config/hypr/fondo-javier.png
#wallpaper = , /home/javier/.config/hypr/fondo-javier.png
#splash = true

wallpaper {
    monitor = eDP-1 
    path = ~/.config/hypr/fondo-javier.png
    fit_mode = fill
##    splash = false
}

