#!/bin/bash
# Script de 09102023.
echo
echo " -== Creando de iso de instalación.  ==-"
echo 
fecha=$(date +%d%m%y)
dirmirror="/home/ftp/Slackware/slackware64-current/"
dirisos="/home/ftp/isos/"
dirrsync="rsync://mirror.slackbuilds.org"
#

cd $dirmirror 

mkisofs -o slackware64-current-install-$fecha.iso -R -J -V "Slackware-current DVD" -hide-rr-moved -hide-joliet-trans-tbl -v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table -sort isolinux/iso.sort -b isolinux/isolinux.bin -c isolinux/isolinux.boot -preparer "Slackware-current build for x86_64 by Javito.>" -publisher "The Slackware Linux Project - http://www.slackware.com/" -x ./pasture -x ./source -x ./extra/source -eltorito-alt-boot -no-emul-boot -eltorito-platform 0xEF -eltorito-boot isolinux/efiboot.img  .

#mkisofs -o slackware64-current-install-$fecha.iso -R -J -V "Slackware-current DVD" -hide-rr-moved -hide-joliet-trans-tbl -v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table -sort isolinux/iso.sort -b isolinux/isolinux.bin -c isolinux/isolinux.boot -preparer "Slackware-current build for x86_64 by Javito.>" -publisher "The Slackware Linux Project - http://www.slackware.com/" -x ./pasture -x ./testing  -x ./source -x ./extra/source -eltorito-alt-boot -no-emul-boot -eltorito-platform 0xEF -eltorito-boot isolinux/efiboot.img  .

echo
echo " -= Moviendo a /home/ftp/isos. =-"

mv slackware64-current-install-$fecha.iso $dirisos

echo
echo
echo
echo " -=  LISTO. =-"

